@baseUrl=http://localhost:3333
@accessToken={{SignIn.response.body.accessToken}}

###
# @name GetHealthCheck
Get {{baseUrl}}/health

###
# @name SignIn
Post {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "document": "03423981059",
  "password": "07101999"
}

###
# @name SignOut
Post {{baseUrl}}/auth/sign-out

###
# @name CheckAuth
Get {{baseUrl}}/auth/status

###
# @name GetCompanyGroups
Get {{baseUrl}}/company-groups

###
# @name GetCompanyGroup
Get {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp
Authorization: Bearer {{accessToken}}

###
# @name CreateCompanyGroup
Post {{baseUrl}}/company-groups
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Grupo empresarial 1",
  "document": "92872357000188",
  "phones": [
    {
      "number": "+5511999999999"
    }
  ]
}

###
# @name UpdateCompanyGroup
Put {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Super grupo empresarial 2",
  "document": "92872357000188"
}

###
# @name DeleteCompanyGroup
Delete {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp
Authorization: Bearer {{accessToken}}

###
# @name CreateCompanyGroupPhoneNumber
Post {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp/phones
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "number": "+5554999859934"
}

###
# @name DeleteCompanyGroupPhoneNumber
Delete {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp/phones/cmgmci5ee0001royspndareir
Authorization: Bearer {{accessToken}}

###
# @name GetCompanies
Get {{baseUrl}}/companies
Authorization: Bearer {{accessToken}}

###
# @name GetCompaniesByCompanyGroupId
Get {{baseUrl}}/companies?companyGroupId=cmgmci5ec0000roys4pmw7gtp
Authorization: Bearer {{accessToken}}

###
# @name GetCompany
Get {{baseUrl}}/companies/cm5abc123def4ghij5klm6nop
Authorization: Bearer {{accessToken}}

###
# @name CreateCompany
Post {{baseUrl}}/companies
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Empresa 1",
  "document": "12345678000199",
  "companyGroupId": "cmgmci5ec0000roys4pmw7gtp",
  "phones": [
    {
      "number": "+5511988887777"
    }
  ]
}

###
# @name UpdateCompany
Put {{baseUrl}}/companies/cm5abc123def4ghij5klm6nop
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Empresa Atualizada",
  "document": "12345678000199"
}

###
# @name DeleteCompany
Delete {{baseUrl}}/companies/cm5abc123def4ghij5klm6nop
Authorization: Bearer {{accessToken}}

###
# @name CreateCompanyPhoneNumber
Post {{baseUrl}}/companies/cm5abc123def4ghij5klm6nop/phones
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "number": "+5521987654321"
}

###
# @name DeleteCompanyPhoneNumber
Delete {{baseUrl}}/companies/cm5abc123def4ghij5klm6nop/phones/cm5xyz789abc0defg1hij2klm
Authorization: Bearer {{accessToken}}

###
# @name GetUnits
Get {{baseUrl}}/units
Authorization: Bearer {{accessToken}}

###
# @name GetUnitsByCompanyId
Get {{baseUrl}}/units?companyId=cm5abc123def4ghij5klm6nop
Authorization: Bearer {{accessToken}}

###
# @name GetUnit
Get {{baseUrl}}/units/cm5unit123def4ghij5klm6xyz
Authorization: Bearer {{accessToken}}

###
# @name CreateUnit
Post {{baseUrl}}/units
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Unidade Centro",
  "document": "98765432000177",
  "companyId": "cm5abc123def4ghij5klm6nop",
  "phones": [
    {
      "number": "+5511977776666"
    }
  ]
}

###
# @name UpdateUnit
Put {{baseUrl}}/units/cm5unit123def4ghij5klm6xyz
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Unidade Centro Atualizada",
  "document": "98765432000177"
}

###
# @name DeleteUnit
Delete {{baseUrl}}/units/cm5unit123def4ghij5klm6xyz
Authorization: Bearer {{accessToken}}

###
# @name CreateUnitPhoneNumber
Post {{baseUrl}}/units/cm5unit123def4ghij5klm6xyz/phones
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "number": "+5511966665555"
}

###
# @name DeleteUnitPhoneNumber
Delete {{baseUrl}}/units/cm5unit123def4ghij5klm6xyz/phones/cm5phone789abc0defg1hij2abc
Authorization: Bearer {{accessToken}}
