@baseUrl=http://localhost:3333
@accessToken={{SignIn.response.body.accessToken}}

###
# @name GetHealthCheck
Get {{baseUrl}}/health

###
# @name SignIn
Post {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "document": "03423981059",
  "password": "07101999"
}

###
# @name SignOut
Post {{baseUrl}}/auth/sign-out

###
# @name CheckAuth
Get {{baseUrl}}/auth/status

###
# @name GetCompanyGroups
Get {{baseUrl}}/company-groups
Authorization: Bearer {{accessToken}}

###
# @name GetCompanyGroup
Get {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp
Authorization: Bearer {{accessToken}}

###
# @name CreateCompanyGroup
Post {{baseUrl}}/company-groups
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Grupo empresarial 1",
  "document": "92872357000188",
  "totalVehiclesHired": 10,
  "phones": [
    {
      "number": "+5511999999999"
    }
  ]
}

###
# @name UpdateCompanyGroup
Put {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Super grupo empresarial 2",
  "document": "92872357000188",
  "totalVehiclesHired": 10
}

###
# @name DeleteCompanyGroup
Delete {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp
Authorization: Bearer {{accessToken}}

###
# @name CreateCompanyGroupPhoneNumber
Post {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp/phones
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "number": "+5554999859934"
}

###
# @name DeleteCompanyGroupPhoneNumber
Delete {{baseUrl}}/company-groups/cmgmci5ec0000roys4pmw7gtp/phones/cmgmci5ee0001royspndareir
Authorization: Bearer {{accessToken}}
