@baseUrl=http://localhost:3333
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWdnaWp3d3QwMDAwcm9nc2s4MHRxa3BtIiwiaWF0IjoxNzU5OTM5NDQxLCJleHAiOjE3NTk5NDEyNDF9.jBgKeNQHgtlt6b3PHdAnDnGQlpGrlH1A2Ou7aBP3i6Nc5U4CcvWY0gdrj5EwtoHWrwsHzEXAC0VOhsR_ehcUY92Omj5Xppb5-bxmXgKTd7SEY_BLwiQxk4ZrsCmsNRC5L_8iuo5DC1xa_cWDoPfTqN8llR1JEKViapQ1_gCi_oCLHUJhtZ-gypvEh_dTLNYw14lRR8UnHg-fwrByVfV42XiTroZymrLRywVwp67KbAAvO4CH99uq5HWWFl0KrJJmCpa42vftkYTJAF1SF1jq5HK0hXj3HX1E-rAdQKK1-WaWCEndGNOFfb0Uh3kvpt_IhcZUJDVIpuBRjpWmliN2RQ

###
# @name GetHealthCheck
Get {{baseUrl}}/health

###
# @name SignIn
Post {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "document": "03423981059",
  "password": "07101999"
}

###
# @name SignOut
Post {{baseUrl}}/auth/sign-out

###
# @name CheckAuth
Get {{baseUrl}}/auth/status